name: Mirror using cron the stemerot.com site and store in this repo a backup

on:
  push:
    branches: 
      - main
  schedule:
    - cron: '0 12 * * *' # Runs at noon UTC every day

# Ensure only one build per branch is running at a time
concurrency:
  group: mirror-stemerot-site
  cancel-in-progress: true

jobs:
  build:
    name: Mirror Stemerot site
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Install wget and httrack
      - name: Install wget and httrack
        run: |
          sudo apt-get update
          sudo apt-get install -y wget httrack

      # Step 3: Clean the directory of the previous mirror
      - name: Clean up previous mirror
        run: |
          ./CLEANUP

      # Step 4: Run wget-stemerot-site.sh script to mirror the site
      - name: Run wget-stemerot-site.sh
        run: |
          mkdir -p stemerot-site-wget/
          touch stemerot-site-wget/file1
          touch stemerot-site-wget/file3
          touch stemerot-site-wget/file2
          touch stemerot-site-wget/file4
          touch wget-logs.txt
          
      # ./wget-stemerot-site.sh

      # Step 5: 
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Archive - $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          branch: website-archives
