name: Mirror using cron the stemerot.com site and store in this repo a backup

on:
  push:
    branches: 
      - main
  schedule:
    - cron: '0 12 * * *' # Runs at noon UTC every day

# Ensure only one build per branch is running at a time
concurrency:
  group: mirror-stemerot-site
  cancel-in-progress: true

jobs:
  mirror-site:
    name: Mirror Stemerot site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
          # The same approach can be used for a different repository
          # repository: 'user/repo'
          # token: ${{ secrets.SECRET_KEY }}
          # fetch-depth: 0

      - name: Install wget and httrack
        run: |
          sudo apt-get update
          sudo apt-get install -y wget httrack

      - name: Clean up previous mirror
        run: |
          ./CLEANUP

      - name: Run wget-stemerot-site.sh
        run: |
          ./wget-stemerot-site.sh

      - name: Archive mirrored site
        run: |
          tar -czvf stemerot-site-archive.tar.gz -C stemerot-site-wget .

      # Upload artifact
      - name: Upload Generated Site
        uses: actions/upload-artifact@v4
        id: upload-mirrored-site
        with:
          name: stemerot-site-archive
          path: stemerot-site-archive.tar.gz

  commit-mirror:
    name: Commit the mirrored site
    runs-on: ubuntu-latest
    needs: mirror-site

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: 'website-archives'
          fetch-depth: 1

      - name: Clean repository directory
        run: |
          rm -rf $(ls)
          pwd
          ls -al

      # Download artifact
      - name: Download Mirrored Site
        uses: actions/download-artifact@v4
        with:
          name: stemerot-site-archive
          path: .

      - name: Extract the site files
        run: |
          tar -xzvf stemerot-site-archive.tar.gz
          rm -rf stemerot-site-archive.tar.gz
          ls -la

      # Commit (in order this to work it needs the following code, see above)
      #     permissions:
      #       contents: write
      - name: Commit mirrored site
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo add
          git add .
          git commit -m "Site extracted on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin website-archives